### ISSUE TITLE
Java 11 Modules, visible-assertions excluded from test classpath

### ISSUE THREAD

**Issue by petrbouda** [rnorth/visible-assertions#19]
https://github.com/petrbouda/surefirevisibilityassertions

When I modularize my application, then visible-assertions are not included, I think the problem is CheckTty.class in the root package which is not compatible with surefire plugin.

**Comment by rnorth** [comment]
Ah ok, thanks for pointing this out. I’ll move this class - it shouldn’t be there. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by petrbouda** [comment]
Thank you :)

**Comment by rnorth** [comment]
I'm releasing this now: https://github.com/rnorth/visible-assertions/releases/tag/2.1.2
